 <div class="footer">
 
 <?php
 
 if(!StrPos(" " . $_SERVER["SCRIPT_NAME"],"/en/")) {
     echo("(c) 2010 Vojtìch Ma¹a, e-mail:
       <a href=\"mailto:kdoSeBojiNeboMiluje@vojtechmasa.com\">kdoSeBojiNeboMiluje@vojtechmasa.com</a>.
       Jakékoli pou¾ití obrázkù, dokumentù, fotografií&hellip; je mo¾né jen se&nbsp;souhlasem autora.");
 } else {
     echo("(c) 2010 Vojtìch Ma¹a, e-mail:
       <a href=\"mailto:whoLovesOrIsAffraidOf@vojtechmasa.com\">whoLovesOrIsAffraidOf@vojtechmasa.com</a>.
       Any usage of pictures, documents, photographs&hellip; is
                    possible with author's permission only.");
 }
 ?>
 
 </div>
